# docker/Dockerfile.docs

FROM node:18-slim

WORKDIR /app/docs

# Copy package manager files from the docs folder
COPY ../docs/package.json ../docs/yarn.lock ./

RUN yarn install --frozen-lockfile
RUN yarn build

# Install serve for static file hosting
RUN yarn global add serve

COPY ../docs .

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
