# docker/Dockerfile.ui

FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY ../pyproject.toml ../uv.lock ./

# Install only UI-related dependencies
RUN uv pip install --system --extra cpu

COPY ../ui ./ui

EXPOSE 7860

CMD ["python", "ui/__init__.py"]
